### ISSUE TITLE
希望能做成netflix的插件

### ISSUE THREAD

**Issue by Ehco1996** [goldengrape/Partial-English-Subtitle-Translation#1]

**Comment by goldengrape** [comment]
呃, 这个对我有点难. 
chrome上有一个Super Netflix的插件, 据说可以外挂字幕:
https://chrome.google.com/webstore/detail/super-netflix/iakpdiefpdniabbekcbofaanjcpjkloe
可以把处理过的字幕当作外挂字幕加载.
